// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { watchtower } from "../models";
import { context } from "../models";

export function CreateOrganisation(arg1: string, arg2: string): Promise<watchtower.OrganisationDTO>;

export function CreateProduct(
	arg1: string,
	arg2: any,
	arg3: number
): Promise<watchtower.ProductDTO>;

export function GetAllOrganisations(): Promise<Array<watchtower.OrganisationDTO>>;

export function GetAllProductsForOrganisation(arg1: number): Promise<Array<watchtower.ProductDTO>>;

export function GetDefaultOrganisation(): Promise<watchtower.OrganisationDTO>;

export function GetProductByID(arg1: number): Promise<watchtower.ProductDTO>;

export function Startup(arg1: context.Context): Promise<void>;

export function UpdateProduct(
	arg1: number,
	arg2: string,
	arg3: any
): Promise<watchtower.ProductDTO>;
