// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {organisations} from '../models';
import {products} from '../models';
import {notifications} from '../models';
import {context} from '../models';

export function CreateOrganisation(arg1:string,arg2:string,arg3:string,arg4:string):Promise<organisations.OrganisationDTO>;

export function CreateProduct(arg1:string,arg2:string,arg3:Array<string>,arg4:number):Promise<products.ProductDTO>;

export function DeleteAllOrgs():Promise<void>;

export function DeleteOldNotifications():Promise<void>;

export function DeleteOrganisation(arg1:number):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function GetAllOrganisations():Promise<Array<organisations.OrganisationDTO>>;

export function GetAllProductsForOrganisation(arg1:number):Promise<Array<products.ProductDTO>>;

export function GetDefaultOrganisation():Promise<organisations.OrganisationDTO>;

export function GetOrganisationByID(arg1:number):Promise<organisations.OrganisationDTO>;

export function GetProductByID(arg1:number):Promise<products.ProductDTO>;

export function GetProductPullRequests(arg1:number):Promise<Array<products.PullRequestDTO>>;

export function GetProductRepos(arg1:number):Promise<Array<products.RepositoryDTO>>;

export function GetPullRequestByOrganisation(arg1:number):Promise<Array<products.PullRequestDTO>>;

export function GetSecurityByOrganisation(arg1:number):Promise<Array<products.SecurityDTO>>;

export function GetSecurityByProductID(arg1:number):Promise<Array<products.SecurityDTO>>;

export function GetUnreadNotifications(arg1:number):Promise<Array<notifications.Notification>>;

export function MarkNotificationAsRead(arg1:number):Promise<void>;

export function SetDefaultOrg(arg1:number):Promise<organisations.OrganisationDTO>;

export function Startup(arg1:context.Context):Promise<void>;

export function SyncOrg(arg1:number):Promise<void>;

export function SyncOrgs():Promise<void>;

export function SyncProduct(arg1:number):Promise<void>;

export function UpdateOrganisation(arg1:organisations.UpdateOrgParams):Promise<organisations.OrganisationDTO>;

export function UpdateProduct(arg1:number,arg2:string,arg3:string,arg4:Array<string>):Promise<products.ProductDTO>;
