// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {watchtower} from '../models';
import {context} from '../models';

export function CreateOrganisation(arg1:string,arg2:string,arg3:string,arg4:string):Promise<watchtower.OrganisationDTO>;

export function CreateProduct(arg1:string,arg2:string,arg3:Array<string>,arg4:number):Promise<watchtower.ProductDTO>;

export function DeleteOrganisation(arg1:number):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function GetAllOrganisations():Promise<Array<watchtower.OrganisationDTO>>;

export function GetAllProductsForOrganisation(arg1:number):Promise<Array<watchtower.ProductDTO>>;

export function GetDefaultOrganisation():Promise<watchtower.OrganisationDTO>;

export function GetOrganisationByID(arg1:number):Promise<watchtower.OrganisationDTO>;

export function GetProductByID(arg1:number):Promise<watchtower.ProductDTO>;

export function GetProductPullRequests(arg1:number):Promise<Array<watchtower.PullRequestDTO>>;

export function GetProductRepos(arg1:number):Promise<Array<watchtower.RepositoryDTO>>;

export function SetDefaultOrg(arg1:number):Promise<watchtower.OrganisationDTO>;

export function Startup(arg1:context.Context):Promise<void>;

export function SyncProduct(arg1:number):Promise<void>;

export function UpdateOrganisation(arg1:watchtower.UpdateOrgParams):Promise<watchtower.OrganisationDTO>;

export function UpdateProduct(arg1:number,arg2:string,arg3:any):Promise<watchtower.ProductDTO>;
