// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOrganisation(arg1, arg2, arg3, arg4) {
  return window['go']['watchtower']['Service']['CreateOrganisation'](arg1, arg2, arg3, arg4);
}

export function CreateProduct(arg1, arg2, arg3, arg4) {
  return window['go']['watchtower']['Service']['CreateProduct'](arg1, arg2, arg3, arg4);
}

export function DeleteOrganisation(arg1) {
  return window['go']['watchtower']['Service']['DeleteOrganisation'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['watchtower']['Service']['DeleteProduct'](arg1);
}

export function GetAllOrganisations() {
  return window['go']['watchtower']['Service']['GetAllOrganisations']();
}

export function GetAllProductsForOrganisation(arg1) {
  return window['go']['watchtower']['Service']['GetAllProductsForOrganisation'](arg1);
}

export function GetDefaultOrganisation() {
  return window['go']['watchtower']['Service']['GetDefaultOrganisation']();
}

export function GetOrganisationByID(arg1) {
  return window['go']['watchtower']['Service']['GetOrganisationByID'](arg1);
}

export function GetProductByID(arg1) {
  return window['go']['watchtower']['Service']['GetProductByID'](arg1);
}

export function GetProductPullRequests(arg1) {
  return window['go']['watchtower']['Service']['GetProductPullRequests'](arg1);
}

export function GetProductRepos(arg1) {
  return window['go']['watchtower']['Service']['GetProductRepos'](arg1);
}

export function GetPullRequestByOrganisation(arg1) {
  return window['go']['watchtower']['Service']['GetPullRequestByOrganisation'](arg1);
}

export function GetSecurityByOrganisation(arg1) {
  return window['go']['watchtower']['Service']['GetSecurityByOrganisation'](arg1);
}

export function GetSecurityByProductID(arg1) {
  return window['go']['watchtower']['Service']['GetSecurityByProductID'](arg1);
}

export function SetDefaultOrg(arg1) {
  return window['go']['watchtower']['Service']['SetDefaultOrg'](arg1);
}

export function Startup(arg1) {
  return window['go']['watchtower']['Service']['Startup'](arg1);
}

export function SyncOrg(arg1) {
  return window['go']['watchtower']['Service']['SyncOrg'](arg1);
}

export function SyncOrgs() {
  return window['go']['watchtower']['Service']['SyncOrgs']();
}

export function SyncProduct(arg1) {
  return window['go']['watchtower']['Service']['SyncProduct'](arg1);
}

export function UpdateOrganisation(arg1) {
  return window['go']['watchtower']['Service']['UpdateOrganisation'](arg1);
}

export function UpdateProduct(arg1, arg2, arg3) {
  return window['go']['watchtower']['Service']['UpdateProduct'](arg1, arg2, arg3);
}
