// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOrganisation(arg1, arg2, arg3) {
  return window['go']['watchtower']['Service']['CreateOrganisation'](arg1, arg2, arg3);
}

export function CreateProduct(arg1, arg2, arg3) {
  return window['go']['watchtower']['Service']['CreateProduct'](arg1, arg2, arg3);
}

export function GetAllOrganisations() {
  return window['go']['watchtower']['Service']['GetAllOrganisations']();
}

export function GetAllProductsForOrganisation(arg1) {
  return window['go']['watchtower']['Service']['GetAllProductsForOrganisation'](arg1);
}

export function GetDefaultOrganisation() {
  return window['go']['watchtower']['Service']['GetDefaultOrganisation']();
}

export function GetProductByID(arg1) {
  return window['go']['watchtower']['Service']['GetProductByID'](arg1);
}

export function SetDefaultOrg(arg1) {
  return window['go']['watchtower']['Service']['SetDefaultOrg'](arg1);
}

export function Startup(arg1) {
  return window['go']['watchtower']['Service']['Startup'](arg1);
}

export function SyncProduct(arg1) {
  return window['go']['watchtower']['Service']['SyncProduct'](arg1);
}

export function UpdateProduct(arg1, arg2, arg3) {
  return window['go']['watchtower']['Service']['UpdateProduct'](arg1, arg2, arg3);
}
