// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Organisation struct {
	ID           int64
	FriendlyName string
	Namespace    string
	DefaultOrg   bool
	CreatedAt    int64
	UpdatedAt    int64
}

type Product struct {
	ID        string
	Name      sql.NullString
	Tags      sql.NullString
	CreatedAt sql.NullInt64
	UpdatedAt sql.NullInt64
}

type ProductOrganisation struct {
	ProductID      sql.NullString
	OrganisationID sql.NullInt64
}

type PullRequest struct {
	ID             string
	ExternalID     sql.NullString
	Title          sql.NullString
	RepositoryName sql.NullString
	Url            sql.NullString
	State          sql.NullString
	Author         sql.NullString
	MergedAt       sql.NullInt64
	CreatedAt      sql.NullInt64
	UpdatedAt      sql.NullInt64
}

type Repository struct {
	ID        string
	Name      sql.NullString
	Url       sql.NullString
	Topic     sql.NullString
	Owner     sql.NullString
	CreatedAt sql.NullInt64
	UpdatedAt sql.NullInt64
}

type Security struct {
	ID             string
	ExternalID     sql.NullString
	RepositoryName sql.NullString
	PackageName    sql.NullString
	State          sql.NullString
	Severity       sql.NullString
	PatchedVersion sql.NullString
	CreatedAt      sql.NullInt64
	UpdatedAt      sql.NullInt64
}
