// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Organisation struct {
	ID           int64
	FriendlyName string
	Description  string
	Namespace    string
	DefaultOrg   bool
	Token        string
	CreatedAt    int64
	UpdatedAt    int64
}

type Product struct {
	ID          int64
	Name        string
	Description string
	Tags        sql.NullString
	CreatedAt   int64
	UpdatedAt   int64
}

type ProductOrganisation struct {
	ProductID      sql.NullInt64
	OrganisationID sql.NullInt64
}

type PullRequest struct {
	ID             int64
	ExternalID     string
	Title          string
	RepositoryName string
	Url            string
	State          string
	Author         string
	MergedAt       sql.NullInt64
	CreatedAt      int64
	UpdatedAt      int64
}

type Repository struct {
	ID        int64
	Name      string
	Url       string
	Topic     string
	Owner     string
	CreatedAt int64
	UpdatedAt int64
}

type Security struct {
	ID             int64
	ExternalID     string
	RepositoryName string
	PackageName    string
	State          string
	Severity       string
	PatchedVersion string
	FixedAt        sql.NullInt64
	CreatedAt      int64
	UpdatedAt      int64
}
