// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package database

import (
	"context"
	"database/sql"
)

const createOrgNotification = `-- name: CreateOrgNotification :one
INSERT INTO organisation_notifications (organisation_id,
                                        type,
                                        content,
                                        created_at,
                                        updated_at)
VALUES (?,
        ?,
        ?,
        CAST(strftime('%s', 'now') AS INTEGER),
        CAST(strftime('%s', 'now') AS INTEGER))
RETURNING id, organisation_id, type, content, status, created_at, updated_at
`

type CreateOrgNotificationParams struct {
	OrganisationID sql.NullInt64
	Type           string
	Content        string
}

func (q *Queries) CreateOrgNotification(ctx context.Context, arg CreateOrgNotificationParams) (OrganisationNotification, error) {
	row := q.db.QueryRowContext(ctx, createOrgNotification, arg.OrganisationID, arg.Type, arg.Content)
	var i OrganisationNotification
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Type,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrgNotificationByDate = `-- name: DeleteOrgNotificationByDate :exec
DELETE FROM organisation_notifications WHERE created_at < ?
`

func (q *Queries) DeleteOrgNotificationByDate(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrgNotificationByDate, createdAt)
	return err
}

const getUnreadNotificationsByOrgID = `-- name: GetUnreadNotificationsByOrgID :many
SELECT id, organisation_id, type, content, status, created_at, updated_at FROM organisation_notifications WHERE organisation_id = ?
AND status = 'unread'
`

func (q *Queries) GetUnreadNotificationsByOrgID(ctx context.Context, organisationID sql.NullInt64) ([]OrganisationNotification, error) {
	rows, err := q.db.QueryContext(ctx, getUnreadNotificationsByOrgID, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganisationNotification
	for rows.Next() {
		var i OrganisationNotification
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Type,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrgNotificationByID = `-- name: UpdateOrgNotificationByID :one
UPDATE organisation_notifications
SET type       = ?,
    content    = ?,
    status     = ?,
    updated_at = CAST(strftime('%s', 'now') AS INTEGER)
WHERE id = ?
RETURNING id, organisation_id, type, content, status, created_at, updated_at
`

type UpdateOrgNotificationByIDParams struct {
	Type    string
	Content string
	Status  string
	ID      int64
}

func (q *Queries) UpdateOrgNotificationByID(ctx context.Context, arg UpdateOrgNotificationByIDParams) (OrganisationNotification, error) {
	row := q.db.QueryRowContext(ctx, updateOrgNotificationByID,
		arg.Type,
		arg.Content,
		arg.Status,
		arg.ID,
	)
	var i OrganisationNotification
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Type,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrgNotificationStatusByID = `-- name: UpdateOrgNotificationStatusByID :one
UPDATE organisation_notifications
SET status     = ?,
    updated_at = CAST(strftime('%s', 'now') AS INTEGER)
WHERE id = ?
RETURNING id, organisation_id, type, content, status, created_at, updated_at
`

type UpdateOrgNotificationStatusByIDParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateOrgNotificationStatusByID(ctx context.Context, arg UpdateOrgNotificationStatusByIDParams) (OrganisationNotification, error) {
	row := q.db.QueryRowContext(ctx, updateOrgNotificationStatusByID, arg.Status, arg.ID)
	var i OrganisationNotification
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Type,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
