// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orgs.sql

package database

import (
	"context"
)

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO organisations (
  friendly_name,
  namespace,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?
)
RETURNING id, friendly_name, namespace, created_at, updated_at
`

type CreateOrganisationParams struct {
	FriendlyName string
	Namespace    string
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRowContext(ctx, createOrganisation,
		arg.FriendlyName,
		arg.Namespace,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.FriendlyName,
		&i.Namespace,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
