// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigFileLocation():Promise<string>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function Version():Promise<string>;
